spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/banking_system
spring.datasource.username=root
spring.datasource.password=Sheh@nsh1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080